### ISSUE TITLE
Repository metadata is wrong in package.json

### ISSUE THREAD

**Issue by valscion** [Developmint/brotli-fsize#1]
I saw that https://www.npmjs.com/package/brotli-fsize links to homepage or repository were both broken. Seems like the repository field in `package.json` is incorrect:

https://github.com/Developmint/brotli-fsize/blob/ac4664fe6ea390666a6d586004d74ed550b58a66/package.json#L6

**Comment by TheAlexLichter** [comment]
@valscion Good point 🙈 Will fix soon, thanks 🙏
